server {
    listen 80;
    server_name nutricore.cloud www.nutricore.cloud;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name nutricore.cloud www.nutricore.cloud;

    ssl_certificate /etc/letsencrypt/live/nutricore.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nutricore.cloud/privkey.pem;

    location / {
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}